name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8.5'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate Report
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml
